<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StartupCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title'                 => 'required|max:225|string',
            'phone'                 => 'required|max:16|string|',
            'price'                 => 'required|integer|',
            'startup_category_id'   => 'required|integer|max:3|',
            'image'                 => 'image',
            'video'                 => 'max:225|string',
            'short_desc'            => 'required|string|',
            'full_desc'             => 'required|string|',
        ];
    }

    public function messages()
    {
        parent::messages(); // TODO: Change the autogenerated stub

        return [
            'title.required'    => 'Это поле обязательно к заполнению',
            'title.max'          => 'Максимальная длинна строки не должна превышать 225 символов',
            'title.string'       => 'Поле должно содежрать хоть одну букву',

            'phone.required'    => 'Это поле обязательно к заполнению',
            'phone.max'          => 'Максимальная длинна строки не должна превышать 16 символов',
            'phone.string'       => 'Поле должно содежрать хоть одну букву',

            'price.required'    => 'Это поле обязательно к заполнению',
            'price.integer'    => 'Это поле должно содержать из цифр',
//            'price.max'          => 'Максимальная длинна строки не должна превышать 20 цифр',

            'startup_category_id.required'    => 'Это поле обязательно к заполнению',
            'startup_category_id.integer'    => 'Это поле должно содержать из цифр',
            'startup_category_id.max'          => 'Максимальная длинна строки не должна превышать 3 цифры',

            'image.image'    => 'Формат изображения должен соответствовать (jpeg, png, bmp, gif, svg, или webp)',

            'video.max'          => 'Максимальная длинна строки не должна превышать 225 символов',
            'video.string'       => 'Поле должно содежрать хоть одну букву',

            'short_desc.required'    => 'Это поле обязательно к заполнению',
            'short_desc.string'       => 'Поле должно содежрать хоть одну букву',

            'full_desc.required'    => 'Это поле обязательно к заполнению',
            'full_desc.string'       => 'Поле должно содежрать хоть одну букву',
        ];
    }
}
